package cl.slimerp.permisos;

public enum Permiso {
    CLIENTES_VER,
    CLIENTES_EDITAR,
    PRODUCTOS_VER,
    PRODUCTOS_EDITAR,
    CATEGORIAS_VER,
    CATEGORIAS_EDITAR,
    BODEGAS_VER,
    BODEGAS_EDITAR,
    USUARIOS_VER,
    USUARIOS_EDITAR,
    EMPRESAS_ADMINISTRAR
}
