package cl.slimerp.permisos;

public enum Permiso {
    CLIENTES_VER,
    CLIENTES_EDITAR,
    PROVEEDORES_VER,
    PROVEEDORES_EDITAR,
    PRODUCTOS_VER,
    PRODUCTOS_EDITAR,
    CATEGORIAS_VER,
    CATEGORIAS_EDITAR,
    BODEGAS_VER,
    BODEGAS_EDITAR,
    FORMAS_PAGO_VER,
    FORMAS_PAGO_EDITAR,
    MOVIMIENTOS_VER,
    MOVIMIENTOS_EDITAR,
    VENTAS_VER,
    VENTAS_EDITAR,
    COMPRAS_VER,
    COMPRAS_EDITAR,
    USUARIOS_VER,
    USUARIOS_EDITAR,
    EMPRESAS_ADMINISTRAR
}
