-- Compras: cabecera simple (proveedor, bodega, total) más el detalle de
-- líneas. Al confirmarse, la compra suma stock a la bodega correspondiente.
-- No tiene relación con la facturación electrónica (folios SII, DTE, XML,
-- etc.); es solo el registro interno de ingreso de mercadería.

CREATE TABLE compra (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(id),
    proveedor_id    BIGINT       NOT NULL REFERENCES proveedor(id),
    bodega_id       BIGINT       NOT NULL REFERENCES bodega(id),
    fecha           TIMESTAMP    NOT NULL DEFAULT now(),
    total           NUMERIC(14,2) NOT NULL DEFAULT 0,
    observacion     VARCHAR(500),
    activo          BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_compra_tenant ON compra(tenant_id);
CREATE INDEX idx_compra_fecha ON compra(tenant_id, fecha);
CREATE INDEX idx_compra_proveedor ON compra(proveedor_id);

CREATE TABLE compra_detalle (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id       BIGINT NOT NULL REFERENCES compra(id),
    producto_id     BIGINT NOT NULL REFERENCES producto(id),
    cantidad        NUMERIC(14,2) NOT NULL,
    precio_unitario NUMERIC(14,2) NOT NULL,
    subtotal        NUMERIC(14,2) NOT NULL
);
CREATE INDEX idx_compra_detalle_compra ON compra_detalle(compra_id);
