-- Tesorería: cuentas por cobrar generadas por ventas a crédito (forma de
-- pago con categoria = CREDITO) y sus transacciones de pago. No tiene
-- relación con la facturación electrónica (folios SII, DTE, XML, etc.).

CREATE TABLE cuenta_por_cobrar (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL REFERENCES tenant(id),
    venta_id            BIGINT       NOT NULL REFERENCES venta(id),
    cliente_id          BIGINT       NOT NULL REFERENCES cliente(id),
    fecha_generacion    TIMESTAMP    NOT NULL DEFAULT now(),
    monto_total         NUMERIC(14,2) NOT NULL,
    monto_pagado        NUMERIC(14,2) NOT NULL DEFAULT 0,
    saldo_pendiente     NUMERIC(14,2) NOT NULL,
    estado              VARCHAR(20)  NOT NULL DEFAULT 'DEUDA',
    fecha_ultimo_pago   TIMESTAMP,
    observaciones       VARCHAR(500),
    usuario_anulo_id    BIGINT REFERENCES usuario(id),
    fecha_anulacion     TIMESTAMP,
    motivo_anulacion    VARCHAR(500),
    CONSTRAINT uq_cuenta_por_cobrar_venta UNIQUE (tenant_id, venta_id),
    CONSTRAINT ck_cuenta_saldo_no_negativo CHECK (saldo_pendiente >= 0),
    CONSTRAINT ck_cuenta_pagado_no_excede CHECK (monto_pagado <= monto_total)
);
CREATE INDEX idx_cuenta_por_cobrar_tenant ON cuenta_por_cobrar(tenant_id);
CREATE INDEX idx_cuenta_por_cobrar_cliente ON cuenta_por_cobrar(tenant_id, cliente_id);
CREATE INDEX idx_cuenta_por_cobrar_estado ON cuenta_por_cobrar(tenant_id, estado);

CREATE TABLE transaccion_pago (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                       BIGINT       NOT NULL REFERENCES tenant(id),
    cuenta_por_cobrar_id            BIGINT       NOT NULL REFERENCES cuenta_por_cobrar(id),
    venta_id                        BIGINT       NOT NULL REFERENCES venta(id),
    cliente_id                      BIGINT       NOT NULL REFERENCES cliente(id),
    fecha                           TIMESTAMP    NOT NULL DEFAULT now(),
    monto                           NUMERIC(14,2) NOT NULL,
    medio_pago                      VARCHAR(20)  NOT NULL,
    estado                          VARCHAR(20)  NOT NULL DEFAULT 'CONFIRMADA',
    usuario_id                      BIGINT REFERENCES usuario(id),
    observaciones                   VARCHAR(500),
    transferencia_banco_origen      VARCHAR(100),
    transferencia_banco_destino     VARCHAR(100),
    transferencia_numero_operacion  VARCHAR(100),
    transferencia_fecha             DATE,
    tarjeta_entidad                 VARCHAR(100),
    tarjeta_tipo                    VARCHAR(50),
    tarjeta_numero_operacion        VARCHAR(100),
    tarjeta_fecha                   DATE,
    cheque_banco                    VARCHAR(100),
    cheque_numero                   VARCHAR(50),
    cheque_fecha_emision            DATE,
    cheque_fecha_pago               DATE,
    usuario_anulo_id                BIGINT REFERENCES usuario(id),
    fecha_anulacion                 TIMESTAMP,
    motivo_anulacion                VARCHAR(500),
    CONSTRAINT ck_transaccion_monto_positivo CHECK (monto > 0)
);
CREATE INDEX idx_transaccion_pago_tenant ON transaccion_pago(tenant_id);
CREATE INDEX idx_transaccion_pago_cuenta ON transaccion_pago(cuenta_por_cobrar_id);
CREATE INDEX idx_transaccion_pago_cliente ON transaccion_pago(tenant_id, cliente_id);
CREATE INDEX idx_transaccion_pago_fecha ON transaccion_pago(tenant_id, fecha);
