CREATE TABLE usuario_permiso (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    usuario_id     BIGINT      NOT NULL REFERENCES usuario(id),
    permiso        VARCHAR(40) NOT NULL,
    fecha_creacion TIMESTAMP   NOT NULL DEFAULT now(),
    UNIQUE (usuario_id, permiso)
);
