-- Slime ERP - esquema inicial (multi-tenant: shared schema + tenant_id)

CREATE TABLE tenant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    rut             VARCHAR(20)  NOT NULL UNIQUE,
    plan            VARCHAR(30)  NOT NULL DEFAULT 'basico',
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_alta      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE usuario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    email           VARCHAR(150) NOT NULL,
    rut             VARCHAR(20)  NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    rol             VARCHAR(30)  NOT NULL DEFAULT 'ADMIN',
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_usuario_tenant_email UNIQUE (tenant_id, email),
    CONSTRAINT uq_usuario_tenant_rut UNIQUE (tenant_id, rut)
);
CREATE INDEX idx_usuario_tenant ON usuario(tenant_id);

CREATE TABLE cliente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    nombre          VARCHAR(150) NOT NULL,
    rut             VARCHAR(20),
    email           VARCHAR(150),
    telefono        VARCHAR(30),
    direccion       VARCHAR(255),
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_cliente_tenant ON cliente(tenant_id);

CREATE TABLE producto (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    sku             VARCHAR(50),
    nombre          VARCHAR(150) NOT NULL,
    descripcion     VARCHAR(500),
    precio_venta    NUMERIC(14,2) NOT NULL DEFAULT 0,
    precio_compra   NUMERIC(14,2) NOT NULL DEFAULT 0,
    stock           NUMERIC(14,2) NOT NULL DEFAULT 0,
    controla_stock  BOOLEAN      NOT NULL DEFAULT TRUE,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_producto_tenant_sku UNIQUE (tenant_id, sku)
);
CREATE INDEX idx_producto_tenant ON producto(tenant_id);

-- Datos de ejemplo para desarrollo local
INSERT INTO tenant (id, nombre, rut, plan)
VALUES (1, 'Empresa Demo', '76.123.456-7', 'basico');

INSERT INTO usuario (tenant_id, email, rut, password_hash, nombre, rol)
VALUES (
    1,
    'admin@demo.cl',
    '15.234.567-8',
    '$2b$10$az9N.tCdIMXWdCSHij.frexWWh0pFR/uyIw60Fda1A6eZi1u2LSce', -- password: admin123
    'Administrador Demo',
    'ADMIN'
);
