-- Cobranza de plataforma: cargos emitidos por el sistema a cada empresa
-- (tenant) por su plan/suscripción y los pagos recibidos de ellas.
-- Es independiente de la tesorería interna de cada empresa (cuenta_por_cobrar).

CREATE TABLE cobranza_empresa (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT       NOT NULL REFERENCES tenant(id),
    concepto           VARCHAR(150) NOT NULL,
    periodo            VARCHAR(20)  NOT NULL,
    monto_total        NUMERIC(14,2) NOT NULL,
    monto_pagado       NUMERIC(14,2) NOT NULL DEFAULT 0,
    saldo_pendiente    NUMERIC(14,2) NOT NULL,
    estado             VARCHAR(20)  NOT NULL DEFAULT 'DEUDA',
    fecha_emision      TIMESTAMP    NOT NULL DEFAULT now(),
    fecha_vencimiento  DATE,
    fecha_ultimo_pago  TIMESTAMP,
    observaciones      VARCHAR(500),
    usuario_admin_id   BIGINT REFERENCES usuario(id),
    fecha_anulacion    TIMESTAMP,
    motivo_anulacion   VARCHAR(500),
    CONSTRAINT ck_cobranza_saldo_no_negativo CHECK (saldo_pendiente >= 0),
    CONSTRAINT ck_cobranza_pagado_no_excede CHECK (monto_pagado <= monto_total)
);
CREATE INDEX idx_cobranza_empresa_tenant ON cobranza_empresa(tenant_id);
CREATE INDEX idx_cobranza_empresa_estado ON cobranza_empresa(tenant_id, estado);

CREATE TABLE cobranza_pago (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cobranza_empresa_id      BIGINT       NOT NULL REFERENCES cobranza_empresa(id),
    tenant_id                BIGINT       NOT NULL REFERENCES tenant(id),
    fecha                    TIMESTAMP    NOT NULL DEFAULT now(),
    monto                    NUMERIC(14,2) NOT NULL,
    medio_pago               VARCHAR(20)  NOT NULL,
    estado                   VARCHAR(20)  NOT NULL DEFAULT 'CONFIRMADA',
    numero_operacion         VARCHAR(100),
    observaciones            VARCHAR(500),
    usuario_admin_id         BIGINT REFERENCES usuario(id),
    fecha_anulacion          TIMESTAMP,
    motivo_anulacion         VARCHAR(500),
    CONSTRAINT ck_cobranza_pago_monto_positivo CHECK (monto > 0)
);
CREATE INDEX idx_cobranza_pago_cuenta ON cobranza_pago(cobranza_empresa_id);
CREATE INDEX idx_cobranza_pago_tenant ON cobranza_pago(tenant_id);
CREATE INDEX idx_cobranza_pago_fecha ON cobranza_pago(tenant_id, fecha);