-- Saavia Admin ERP: esquema administrativo propio (separado de los datos operacionales del ERP).
-- El backend de negocio (Flyway) sigue siendo el único dueño del DDL.

CREATE SCHEMA IF NOT EXISTS admin;

-- Usuario administrativo (RBAC de plataforma). Separado de `usuario` (ERP).
CREATE TABLE admin.usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(150) NOT NULL,
    email          VARCHAR(150) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    rol            VARCHAR(30)  NOT NULL,   -- SUPER_ADMIN ADMIN SUPPORT FINANCE AUDITOR
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    ultimo_acceso  TIMESTAMP,
    fecha_creacion TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE admin.sesion (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_usuario_id BIGINT       NOT NULL REFERENCES admin.usuario(id),
    token_hash       VARCHAR(255) NOT NULL,
    ip               VARCHAR(45),
    user_agent       VARCHAR(500),
    creada_en        TIMESTAMP    NOT NULL DEFAULT now(),
    expira_en        TIMESTAMP    NOT NULL,
    revocada_en      TIMESTAMP
);
CREATE INDEX idx_admin_sesion_usuario ON admin.sesion(admin_usuario_id);

-- Columnas administrativas sobre el tenant. El ERP solo lee activo/plan/fecha_alta,
-- de modo que estos cambios son aditivos y no alteran sus contratos.
ALTER TABLE tenant ADD COLUMN status         VARCHAR(20)  NOT NULL DEFAULT 'TRIAL';
ALTER TABLE tenant ADD COLUMN business_name  VARCHAR(150);
ALTER TABLE tenant ADD COLUMN last_access_at TIMESTAMP;
CREATE INDEX idx_tenant_status ON tenant(status);

-- Seed: SUPER_ADMIN administrativo (mismas credenciales que el seed V23: password Super123!)
INSERT INTO admin.usuario (nombre, email, password_hash, rol, activo)
VALUES ('Super Administrador', 'super@slimerp.cl',
        '$2b$10$qoxzrj3gH5e05XaFkk5ntuCzsk8tkj82nQEkmZkjs900M0PJ6rFZm',
        'SUPER_ADMIN', TRUE);