-- Saavia Admin ERP: catálogo de planes y suscripciones de la plataforma.

CREATE TABLE admin.plan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100)  NOT NULL,
    descripcion     VARCHAR(500),
    precio_mensual  NUMERIC(14,2) NOT NULL,
    precio_anual    NUMERIC(14,2),
    max_usuarios    INTEGER       NOT NULL,
    max_documentos  INTEGER       NOT NULL,
    modulos         JSONB         NOT NULL,
    caracteristicas JSONB,
    estado          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE'  -- ACTIVE | INACTIVE
);

CREATE TABLE admin.suscripcion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT        NOT NULL REFERENCES tenant(id),
    plan_id             BIGINT        NOT NULL REFERENCES admin.plan(id),
    estado              VARCHAR(30)   NOT NULL, -- TRIAL ACTIVE PAST_DUE SUSPENDED CANCELLED EXPIRED
    fecha_inicio        DATE          NOT NULL,
    fecha_vencimiento   DATE          NOT NULL,
    ciclo_facturacion   VARCHAR(20)   NOT NULL, -- MONTHLY | ANNUAL
    precio              NUMERIC(14,2) NOT NULL,
    periodo_gracia_dias INTEGER       NOT NULL DEFAULT 0
);
CREATE INDEX idx_suscripcion_company ON admin.suscripcion(company_id);
CREATE INDEX idx_suscripcion_venc   ON admin.suscripcion(estado, fecha_vencimiento);

INSERT INTO admin.plan (nombre, descripcion, precio_mensual, precio_anual, max_usuarios, max_documentos, modulos, caracteristicas, estado)
VALUES
 ('Basico',      'Para operaciones pequeñas', 15990, 159900,  3,   500,  '["ventas","compras"]'::jsonb, NULL, 'ACTIVE'),
 ('Profesional', 'Para pymes en crecimiento', 29990, 299900, 10,  1000, '["ventas","compras","inventario","contabilidad","dte"]'::jsonb, NULL, 'ACTIVE'),
 ('Empresa',     'Para organizaciones grandes', 59990, 599900, 50,  5000, '["ventas","compras","inventario","contabilidad","dte"]'::jsonb, NULL, 'ACTIVE');