-- Saavia Admin ERP: pagos y alertas de la plataforma.

CREATE TABLE admin.pago (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT        NOT NULL REFERENCES tenant(id),
    suscripcion_id     BIGINT        REFERENCES admin.suscripcion(id),
    monto              NUMERIC(14,2) NOT NULL,
    moneda             VARCHAR(10)   NOT NULL DEFAULT 'CLP',
    metodo             VARCHAR(30)   NOT NULL,
    estado             VARCHAR(20)   NOT NULL, -- PENDING PAID FAILED REFUNDED CANCELLED
    referencia_externa VARCHAR(150),
    pagado_en          TIMESTAMP,
    creado_por         BIGINT        REFERENCES admin.usuario(id),
    creado_en          TIMESTAMP     NOT NULL DEFAULT now()
);
CREATE INDEX idx_pago_company ON admin.pago(company_id);

CREATE TABLE admin.alerta (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT        REFERENCES tenant(id),
    severity    VARCHAR(20)   NOT NULL, -- CRITICAL WARNING INFO
    tipo        VARCHAR(40)   NOT NULL,
    titulo      VARCHAR(200)  NOT NULL,
    descripcion VARCHAR(1000),
    status      VARCHAR(20)   NOT NULL DEFAULT 'OPEN', -- OPEN READ RESOLVED
    creada_en   TIMESTAMP     NOT NULL DEFAULT now(),
    leida_en    TIMESTAMP,
    resuelta_en TIMESTAMP
);
CREATE INDEX idx_alerta_estado ON admin.alerta(status, severity);