-- Saavia Admin ERP: auditoría, soporte (tickets) y configuración global.

CREATE TABLE admin.audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_usuario_id BIGINT REFERENCES admin.usuario(id),
    company_id       BIGINT REFERENCES tenant(id),
    action           VARCHAR(60) NOT NULL,
    modulo           VARCHAR(60) NOT NULL,
    entity_type      VARCHAR(60),
    entity_id        BIGINT,
    old_value        JSONB,
    new_value        JSONB,
    ip_address       VARCHAR(45),
    user_agent       VARCHAR(500),
    creado_en        TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_fecha  ON admin.audit_log(creado_en DESC);
CREATE INDEX idx_audit_company ON admin.audit_log(company_id);

CREATE TABLE admin.ticket_soporte (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT REFERENCES tenant(id),
    user_id         BIGINT REFERENCES usuario(id),
    subject         VARCHAR(200)  NOT NULL,
    descripcion     VARCHAR(2000),
    categoria       VARCHAR(60),
    prioridad       VARCHAR(20)   NOT NULL DEFAULT 'MEDIUM', -- LOW MEDIUM HIGH CRITICAL
    status          VARCHAR(20)   NOT NULL DEFAULT 'OPEN',   -- OPEN IN_PROGRESS WAITING RESOLVED CLOSED
    assigned_to     BIGINT REFERENCES admin.usuario(id),
    creado_en       TIMESTAMP     NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMP,
    resuelto_en     TIMESTAMP
);

CREATE TABLE admin.configuracion (
    clave            VARCHAR(80) PRIMARY KEY,
    valor            JSONB        NOT NULL,
    descripcion      VARCHAR(300),
    actualizado_en   TIMESTAMP    NOT NULL DEFAULT now(),
    actualizado_por  BIGINT REFERENCES admin.usuario(id)
);

INSERT INTO admin.configuracion (clave, valor, descripcion) VALUES
 ('plataforma.nombre',           '{"nombre":"Saavia Admin"}'::jsonb, 'Nombre de la plataforma'),
 ('suscripcion.gracePeriodDays', '{"gracePeriodDays":7}'::jsonb,     'Periodo de gracia dias'),
 ('suscripcion.trialDays',       '{"trialDays":14}'::jsonb,          'Dias de prueba');