-- Módulo de Gastos: categorías, gastos puntuales y plantillas recurrentes.
-- No genera Cuenta por Pagar en esta migración; eso llega en una migración
-- posterior (V30__cuentas_por_pagar.sql) que referencia la tabla `gasto`.

CREATE TABLE categoria_gasto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_categoria_gasto_tenant_nombre UNIQUE (tenant_id, nombre)
);

CREATE TABLE gasto_recurrente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    categoria_gasto_id BIGINT NOT NULL REFERENCES categoria_gasto(id),
    monto NUMERIC(14,2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    dia_mes SMALLINT NOT NULL CHECK (dia_mes BETWEEN 1 AND 28),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE gasto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    categoria_gasto_id BIGINT NOT NULL REFERENCES categoria_gasto(id),
    gasto_recurrente_id BIGINT REFERENCES gasto_recurrente(id),
    monto NUMERIC(14,2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    fecha DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_gasto_tenant_fecha ON gasto (tenant_id, fecha);
CREATE INDEX idx_gasto_recurrente_origen ON gasto (gasto_recurrente_id);
