-- Cuentas por Pagar: deuda generada por documentos de compra y por gastos
-- (puntuales o recurrentes), con pagos parciales registrados en
-- transaccion_pago_compra. Origen exclusivo: compra_id o gasto_id, nunca
-- ambos (ver CHECK). proveedor_id/categoria_gasto_id se denormalizan desde
-- el origen para poder filtrar/agrupar sin join, igual que cuenta_por_cobrar
-- denormaliza cliente_id desde venta.

CREATE TABLE cuenta_por_pagar (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL REFERENCES tenant(id),
    compra_id           BIGINT REFERENCES compra(id),
    gasto_id            BIGINT REFERENCES gasto(id),
    proveedor_id        BIGINT REFERENCES proveedor(id),
    categoria_gasto_id  BIGINT REFERENCES categoria_gasto(id),
    descripcion         VARCHAR(255) NOT NULL,
    fecha_generacion    TIMESTAMP    NOT NULL DEFAULT now(),
    monto_total         NUMERIC(14,2) NOT NULL,
    monto_pagado        NUMERIC(14,2) NOT NULL DEFAULT 0,
    saldo_pendiente     NUMERIC(14,2) NOT NULL,
    estado              VARCHAR(20)  NOT NULL DEFAULT 'DEUDA',
    fecha_ultimo_pago   TIMESTAMP,
    observaciones       VARCHAR(500),
    usuario_anulo_id    BIGINT REFERENCES usuario(id),
    fecha_anulacion     TIMESTAMP,
    motivo_anulacion    VARCHAR(500),
    CONSTRAINT ck_cxp_un_origen CHECK (
        (compra_id IS NOT NULL AND gasto_id IS NULL) OR
        (compra_id IS NULL AND gasto_id IS NOT NULL)
    ),
    CONSTRAINT ck_cxp_saldo_no_negativo CHECK (saldo_pendiente >= 0),
    CONSTRAINT ck_cxp_pagado_no_excede CHECK (monto_pagado <= monto_total)
);
CREATE UNIQUE INDEX uq_cxp_compra ON cuenta_por_pagar(tenant_id, compra_id) WHERE compra_id IS NOT NULL;
CREATE UNIQUE INDEX uq_cxp_gasto ON cuenta_por_pagar(tenant_id, gasto_id) WHERE gasto_id IS NOT NULL;
CREATE INDEX idx_cxp_tenant_estado ON cuenta_por_pagar(tenant_id, estado);
CREATE INDEX idx_cxp_proveedor ON cuenta_por_pagar(tenant_id, proveedor_id);
CREATE INDEX idx_cxp_categoria_gasto ON cuenta_por_pagar(tenant_id, categoria_gasto_id);

CREATE TABLE transaccion_pago_compra (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                       BIGINT       NOT NULL REFERENCES tenant(id),
    cuenta_por_pagar_id             BIGINT       NOT NULL REFERENCES cuenta_por_pagar(id),
    compra_id                       BIGINT,
    gasto_id                        BIGINT,
    fecha                           TIMESTAMP    NOT NULL DEFAULT now(),
    monto                           NUMERIC(14,2) NOT NULL,
    medio_pago                      VARCHAR(20)  NOT NULL,
    estado                          VARCHAR(20)  NOT NULL DEFAULT 'CONFIRMADA',
    usuario_id                      BIGINT REFERENCES usuario(id),
    observaciones                   VARCHAR(500),
    transferencia_banco_origen      VARCHAR(100),
    transferencia_banco_destino     VARCHAR(100),
    transferencia_numero_operacion  VARCHAR(100),
    transferencia_fecha             DATE,
    tarjeta_entidad                 VARCHAR(100),
    tarjeta_tipo                    VARCHAR(50),
    tarjeta_numero_operacion        VARCHAR(100),
    tarjeta_fecha                   DATE,
    cheque_banco                    VARCHAR(100),
    cheque_numero                   VARCHAR(50),
    cheque_fecha_emision            DATE,
    cheque_fecha_pago               DATE,
    usuario_anulo_id                BIGINT REFERENCES usuario(id),
    fecha_anulacion                 TIMESTAMP,
    motivo_anulacion                VARCHAR(500),
    CONSTRAINT ck_pago_compra_monto_positivo CHECK (monto > 0)
);
CREATE INDEX idx_pago_compra_tenant ON transaccion_pago_compra(tenant_id);
CREATE INDEX idx_pago_compra_cuenta ON transaccion_pago_compra(cuenta_por_pagar_id);
CREATE INDEX idx_pago_compra_fecha ON transaccion_pago_compra(tenant_id, fecha);
