-- Módulo de Cotizaciones: primer eslabón de la trazabilidad comercial
-- (Cotización -> Nota de Venta -> Guía -> Factura -> Pago). Una cotización no
-- compromete stock ni genera deuda: es un documento comercial con estados.
--
-- El número (COT-000123) se arma en la aplicación a partir de "folio", que es
-- un correlativo por tenant servido por cotizacion_folio_contador. Se asigna al
-- crear y nunca se reutiliza: borrar un borrador deja un hueco, igual que un
-- documento anulado.

CREATE TABLE cotizacion_folio_contador (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT  NOT NULL REFERENCES tenant(id),
    ultimo_folio INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_cotizacion_folio_tenant UNIQUE (tenant_id)
);

CREATE TABLE cotizacion (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               BIGINT        NOT NULL REFERENCES tenant(id),
    folio                   INTEGER       NOT NULL,
    cliente_id              BIGINT        NOT NULL REFERENCES cliente(id),
    vendedor_id             BIGINT        NOT NULL REFERENCES usuario(id),
    forma_pago_id           BIGINT        REFERENCES forma_pago(id),
    estado                  VARCHAR(20)   NOT NULL DEFAULT 'BORRADOR',
    exenta                  BOOLEAN       NOT NULL DEFAULT false,
    fecha_emision           DATE          NOT NULL,
    fecha_vencimiento       DATE          NOT NULL,
    descuento               NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_subtotal          NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_descuento         NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_neto              NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_iva               NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_total             NUMERIC(14,2) NOT NULL DEFAULT 0,
    condiciones_comerciales VARCHAR(500),
    observaciones           VARCHAR(500),
    motivo                  VARCHAR(500),
    fecha_creacion          TIMESTAMP     NOT NULL DEFAULT now(),
    fecha_actualizacion     TIMESTAMP,
    CONSTRAINT uq_cotizacion_tenant_folio UNIQUE (tenant_id, folio),
    CONSTRAINT ck_cotizacion_vigencia CHECK (fecha_vencimiento >= fecha_emision),
    CONSTRAINT ck_cotizacion_descuento_no_negativo CHECK (descuento >= 0)
);
CREATE INDEX idx_cotizacion_tenant_estado ON cotizacion(tenant_id, estado);
CREATE INDEX idx_cotizacion_tenant_fecha ON cotizacion(tenant_id, fecha_emision);
CREATE INDEX idx_cotizacion_cliente ON cotizacion(tenant_id, cliente_id);
CREATE INDEX idx_cotizacion_vendedor ON cotizacion(tenant_id, vendedor_id);

-- codigo y descripcion son un snapshot del producto al momento de guardar: la
-- cotización es un documento histórico y el catálogo cambia con el tiempo.
CREATE TABLE cotizacion_detalle (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id   BIGINT        NOT NULL REFERENCES cotizacion(id) ON DELETE CASCADE,
    producto_id     BIGINT        NOT NULL REFERENCES producto(id),
    codigo          VARCHAR(50),
    descripcion     VARCHAR(255)  NOT NULL,
    cantidad        NUMERIC(14,2) NOT NULL,
    precio_unitario NUMERIC(14,2) NOT NULL,
    descuento       NUMERIC(14,2) NOT NULL DEFAULT 0,
    subtotal        NUMERIC(14,2) NOT NULL,
    CONSTRAINT ck_cotizacion_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_cotizacion_detalle_precio CHECK (precio_unitario >= 0),
    CONSTRAINT ck_cotizacion_detalle_descuento CHECK (descuento >= 0)
);
CREATE INDEX idx_cotizacion_detalle_cotizacion ON cotizacion_detalle(cotizacion_id);

-- Historial append-only de la cotización. usuario_id es nullable porque el job
-- que marca las cotizaciones vencidas no actúa en nombre de ningún usuario.
CREATE TABLE cotizacion_evento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL REFERENCES tenant(id),
    cotizacion_id   BIGINT      NOT NULL REFERENCES cotizacion(id) ON DELETE CASCADE,
    usuario_id      BIGINT      REFERENCES usuario(id),
    accion          VARCHAR(30) NOT NULL,
    estado_anterior VARCHAR(20),
    estado_nuevo    VARCHAR(20),
    detalle         VARCHAR(500),
    fecha           TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX idx_cotizacion_evento_cotizacion ON cotizacion_evento(cotizacion_id, fecha);
