-- Documentos generados a partir de una cotización: el enganche de la cadena
-- Cotización -> Nota de Venta -> Guía de Despacho -> Factura -> Pago.
--
-- Nace vacía a propósito: hoy aceptar una cotización solo cambia su estado y
-- ningún módulo escribe todavía en esta tabla. Existe para que cuando aparezca
-- Nota de Venta el vínculo ya tenga dónde guardarse, sin migrar datos ni tocar
-- la cotización.
CREATE TABLE cotizacion_documento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    cotizacion_id  BIGINT      NOT NULL REFERENCES cotizacion(id) ON DELETE CASCADE,
    tipo_documento VARCHAR(30) NOT NULL,
    documento_id   BIGINT      NOT NULL,
    numero         VARCHAR(50),
    fecha          TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_cotizacion_documento UNIQUE (tenant_id, cotizacion_id, tipo_documento, documento_id)
);
CREATE INDEX idx_cotizacion_documento_cotizacion ON cotizacion_documento(cotizacion_id, fecha);
