-- Módulo de Notas de Venta: segundo eslabón de la trazabilidad comercial
-- (Cotización -> Nota de Venta -> Guía -> Factura -> Pago). La nota de venta
-- representa la operación confirmada; NO compromete stock ni genera deuda:
-- eso sucede al despachar (Guía) o facturar (DTE).
--
-- El número (NV-000045) se arma en la aplicación a partir de "folio", un
-- correlativo por tenant servido por nota_venta_folio_contador. Se asigna al
-- crear y nunca se reutiliza: borrar un borrador deja un hueco, igual que en
-- cotizaciones.
--
-- El origen puede ser una cotización aceptada (origen=COTIZACION, cotizacion_id
-- apunta a la cotización) o una venta directa (origen=VENTA_DIRECTA). El vínculo
-- inverso queda en cotizacion_documento (tipo NOTA_VENTA) para no depender de
-- campos del tipo invoice_id.

CREATE TABLE nota_venta_folio_contador (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT  NOT NULL REFERENCES tenant(id),
    ultimo_folio INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_nota_venta_folio_tenant UNIQUE (tenant_id)
);

CREATE TABLE nota_venta (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT        NOT NULL REFERENCES tenant(id),
    folio                 INTEGER       NOT NULL,
    cliente_id            BIGINT        NOT NULL REFERENCES cliente(id),
    vendedor_id           BIGINT        NOT NULL REFERENCES usuario(id),
    forma_pago_id         BIGINT        REFERENCES forma_pago(id),
    origen                VARCHAR(20)   NOT NULL DEFAULT 'VENTA_DIRECTA',
    cotizacion_id         BIGINT        REFERENCES cotizacion(id),
    estado                VARCHAR(30)   NOT NULL DEFAULT 'BORRADOR',
    exenta                BOOLEAN       NOT NULL DEFAULT false,
    moneda                VARCHAR(10)   NOT NULL DEFAULT 'CLP',
    fecha_emision         DATE          NOT NULL,
    fecha_entrega_estimada DATE,
    direccion_entrega     VARCHAR(255),
    condiciones_venta     VARCHAR(500),
    observaciones         VARCHAR(500),
    motivo                VARCHAR(500),
    descuento             NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_subtotal        NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_descuento       NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_neto            NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_iva             NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_total           NUMERIC(14,2) NOT NULL DEFAULT 0,
    fecha_creacion        TIMESTAMP     NOT NULL DEFAULT now(),
    fecha_actualizacion   TIMESTAMP,
    CONSTRAINT uq_nota_venta_tenant_folio UNIQUE (tenant_id, folio),
    CONSTRAINT ck_nota_venta_descuento_no_negativo CHECK (descuento >= 0)
);
CREATE INDEX idx_nota_venta_tenant_estado ON nota_venta(tenant_id, estado);
CREATE INDEX idx_nota_venta_tenant_fecha ON nota_venta(tenant_id, fecha_emision);
CREATE INDEX idx_nota_venta_cliente ON nota_venta(tenant_id, cliente_id);
CREATE INDEX idx_nota_venta_vendedor ON nota_venta(tenant_id, vendedor_id);
CREATE INDEX idx_nota_venta_cotizacion ON nota_venta(tenant_id, cotizacion_id);

-- codigo y descripcion son un snapshot del producto al momento de guardar: la
-- nota de venta es un documento histórico y el catálogo cambia con el tiempo.
-- cantidad_entregada es la base del control de entregas parciales: el estado
-- (PARCIALMENTE ENTREGADA / ENTREGADA) se deriva de la comparación entre la
-- cantidad solicitada y la entregada.
CREATE TABLE nota_venta_detalle (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_venta_id     BIGINT        NOT NULL REFERENCES nota_venta(id) ON DELETE CASCADE,
    producto_id       BIGINT        NOT NULL REFERENCES producto(id),
    codigo            VARCHAR(50),
    descripcion       VARCHAR(255)  NOT NULL,
    cantidad          NUMERIC(14,2) NOT NULL,
    cantidad_entregada NUMERIC(14,2) NOT NULL DEFAULT 0,
    precio_unitario   NUMERIC(14,2) NOT NULL,
    descuento         NUMERIC(14,2) NOT NULL DEFAULT 0,
    subtotal          NUMERIC(14,2) NOT NULL,
    CONSTRAINT ck_nota_venta_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_nota_venta_detalle_precio CHECK (precio_unitario >= 0),
    CONSTRAINT ck_nota_venta_detalle_descuento CHECK (descuento >= 0),
    CONSTRAINT ck_nota_venta_detalle_entregado CHECK (cantidad_entregada >= 0)
);
CREATE INDEX idx_nota_venta_detalle_nota ON nota_venta_detalle(nota_venta_id);

-- Cabecera de un avance de entrega: registrar entregas parciales va dejando
-- asentada la trazabilidad de qué se entregó y cuándo. El módulo de Guía de
-- Despacho futuro reemplazará este mecanismo por su documento formal.
CREATE TABLE nota_venta_entrega (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    nota_venta_id  BIGINT      NOT NULL REFERENCES nota_venta(id) ON DELETE CASCADE,
    fecha          TIMESTAMP   NOT NULL DEFAULT now(),
    observacion    VARCHAR(500),
    usuario_id     BIGINT      REFERENCES usuario(id)
);
CREATE INDEX idx_nota_venta_entrega_nota ON nota_venta_entrega(nota_venta_id, fecha);

CREATE TABLE nota_venta_entrega_linea (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrega_id    BIGINT        NOT NULL REFERENCES nota_venta_entrega(id) ON DELETE CASCADE,
    producto_id   BIGINT        NOT NULL REFERENCES producto(id),
    cantidad      NUMERIC(14,2) NOT NULL,
    CONSTRAINT ck_nota_venta_entrega_linea_cantidad CHECK (cantidad > 0)
);
CREATE INDEX idx_nota_venta_entrega_linea_entrega ON nota_venta_entrega_linea(entrega_id);

-- Historial append-only de la nota de venta. usuario_id es nullable porque
-- algunos procesos automáticos pueden no actuar en nombre de un usuario.
CREATE TABLE nota_venta_evento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL REFERENCES tenant(id),
    nota_venta_id   BIGINT      NOT NULL REFERENCES nota_venta(id) ON DELETE CASCADE,
    usuario_id      BIGINT      REFERENCES usuario(id),
    accion          VARCHAR(30) NOT NULL,
    estado_anterior VARCHAR(30),
    estado_nuevo    VARCHAR(30),
    detalle         VARCHAR(500),
    fecha           TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX idx_nota_venta_evento_nota ON nota_venta_evento(nota_venta_id, fecha);

-- Documentos generados a partir de una nota de venta: el enganche hacia Guía de
-- Despacho, Factura y Pago. Nace vacía a propósito; hoy ningún módulo escribe
-- todavía aquí. Existe para que cuando aparezcan esos módulos el vínculo ya
-- tenga dónde guardarse sin migrar datos ni tocar la nota de venta.
CREATE TABLE nota_venta_documento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT      NOT NULL REFERENCES tenant(id),
    nota_venta_id  BIGINT      NOT NULL REFERENCES nota_venta(id) ON DELETE CASCADE,
    tipo_documento VARCHAR(30) NOT NULL,
    documento_id   BIGINT      NOT NULL,
    numero         VARCHAR(50),
    fecha          TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_nota_venta_documento UNIQUE (tenant_id, nota_venta_id, tipo_documento, documento_id)
);
CREATE INDEX idx_nota_venta_documento_nota ON nota_venta_documento(nota_venta_id, fecha);