-- Módulo de Nota de Crédito: el documento que corrige hacia atrás la cadena
-- comercial (Cotización -> Nota de Venta -> Venta). Toda nota de crédito corrige
-- una VENTA (Boleta/Factura/Voucher), que es el único documento del ERP que
-- descuenta stock y por lo tanto el único donde la recuperación de inventario
-- tiene sentido.
--
-- El número (NC-000012) se arma en la aplicación a partir de "folio", un
-- correlativo por tenant servido por nota_credito_folio_contador. Se asigna al
-- crear y nunca se reutiliza: borrar un borrador deja un hueco, igual que en
-- cotizaciones y notas de venta.
--
-- Alcance deliberado: sin XML, DTE, CAF ni envío al SII, y sin efectos sobre
-- cuentas por cobrar ni tesorería. La nota de crédito registra montos, corrige
-- el documento asociado y recupera inventario; nada más.

CREATE TABLE nota_credito_folio_contador (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT  NOT NULL REFERENCES tenant(id),
    ultimo_folio INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_nota_credito_folio_tenant UNIQUE (tenant_id)
);

-- El documento asociado se guarda dos veces a propósito: venta_id es la FK dura
-- que permite navegar al documento vivo, y las columnas doc_asociado_* son un
-- snapshot del momento en que se creó la nota. La nota de crédito es un
-- documento histórico: aunque la venta cambie, debe seguir mostrando qué se
-- corrigió.
--
-- cliente_id, bodega_id y exenta también se copian de la venta: el cliente es
-- siempre el mismo, la mercadería vuelve a la bodega desde la que salió, y la
-- base impositiva debe coincidir con la del documento corregido para que los
-- montos cuadren.
CREATE TABLE nota_credito (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT        NOT NULL REFERENCES tenant(id),
    folio               INTEGER       NOT NULL,
    cliente_id          BIGINT        NOT NULL REFERENCES cliente(id),
    usuario_id          BIGINT        NOT NULL REFERENCES usuario(id),
    estado              VARCHAR(20)   NOT NULL DEFAULT 'BORRADOR',
    tipo_correccion     VARCHAR(20)   NOT NULL,
    fecha               DATE          NOT NULL,
    motivo              VARCHAR(500),
    observaciones       VARCHAR(500),
    -- Solo se usa cuando tipo_correccion = 'CORRIGE_TEXTO'.
    texto_correccion    VARCHAR(2000),
    bodega_id           BIGINT        REFERENCES bodega(id),
    exenta              BOOLEAN       NOT NULL DEFAULT false,
    moneda              VARCHAR(10)   NOT NULL DEFAULT 'CLP',

    -- Documento asociado: FK dura + snapshot histórico.
    venta_id            BIGINT        NOT NULL REFERENCES venta(id),
    doc_asociado_tipo   VARCHAR(20)   NOT NULL,
    doc_asociado_folio  INTEGER,
    doc_asociado_fecha  DATE,
    doc_asociado_razon  VARCHAR(500),

    -- Todos los montos se guardan positivos: el signo semántico lo da el tipo de
    -- documento, una nota de crédito por definición resta.
    descuento           NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_subtotal      NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_descuento     NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_neto          NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_iva           NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_total         NUMERIC(14,2) NOT NULL DEFAULT 0,

    fecha_emision       TIMESTAMP,
    fecha_anulacion     TIMESTAMP,
    fecha_creacion      TIMESTAMP     NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT uq_nota_credito_tenant_folio UNIQUE (tenant_id, folio),
    CONSTRAINT ck_nota_credito_descuento_no_negativo CHECK (descuento >= 0)
);
CREATE INDEX idx_nota_credito_tenant_estado ON nota_credito(tenant_id, estado);
CREATE INDEX idx_nota_credito_tenant_fecha  ON nota_credito(tenant_id, fecha);
CREATE INDEX idx_nota_credito_cliente       ON nota_credito(tenant_id, cliente_id);
CREATE INDEX idx_nota_credito_venta         ON nota_credito(tenant_id, venta_id);
CREATE INDEX idx_nota_credito_tipo          ON nota_credito(tenant_id, tipo_correccion);

-- codigo y descripcion son un snapshot del producto al momento de guardar: el
-- catálogo cambia con el tiempo y el documento no.
--
-- venta_detalle_id es nullable porque una corrección puede incluir una línea que
-- no estaba en el documento original; esas líneas no pueden recuperar inventario
-- (no hay cantidad vendida contra la cual validar). El índice sobre esta columna
-- es el que sostiene la consulta que impide recuperar dos veces lo mismo.
CREATE TABLE nota_credito_detalle (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_credito_id     BIGINT        NOT NULL REFERENCES nota_credito(id) ON DELETE CASCADE,
    producto_id         BIGINT        NOT NULL REFERENCES producto(id),
    venta_detalle_id    BIGINT        REFERENCES venta_detalle(id),
    codigo              VARCHAR(50),
    descripcion         VARCHAR(255)  NOT NULL,
    cantidad            NUMERIC(14,2) NOT NULL,
    precio_unitario     NUMERIC(14,2) NOT NULL,
    descuento           NUMERIC(14,2) NOT NULL DEFAULT 0,
    subtotal            NUMERIC(14,2) NOT NULL,
    recupera_inventario BOOLEAN       NOT NULL DEFAULT false,
    CONSTRAINT ck_nota_credito_detalle_cantidad  CHECK (cantidad > 0),
    CONSTRAINT ck_nota_credito_detalle_precio    CHECK (precio_unitario >= 0),
    CONSTRAINT ck_nota_credito_detalle_descuento CHECK (descuento >= 0)
);
CREATE INDEX idx_nota_credito_detalle_nota ON nota_credito_detalle(nota_credito_id);
CREATE INDEX idx_nota_credito_detalle_vd   ON nota_credito_detalle(venta_detalle_id);

-- Historial append-only de la nota de crédito. usuario_id es nullable porque
-- algunos procesos automáticos pueden no actuar en nombre de un usuario.
CREATE TABLE nota_credito_evento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL REFERENCES tenant(id),
    nota_credito_id BIGINT      NOT NULL REFERENCES nota_credito(id) ON DELETE CASCADE,
    usuario_id      BIGINT      REFERENCES usuario(id),
    accion          VARCHAR(30) NOT NULL,
    estado_anterior VARCHAR(20),
    estado_nuevo    VARCHAR(20),
    detalle         VARCHAR(500),
    fecha           TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX idx_nota_credito_evento_nota ON nota_credito_evento(nota_credito_id, fecha);

-- Vínculo explícito entre la nota de crédito y los movimientos de inventario que
-- generó. Existe porque movimiento_inventario.referencia_id es un id "desnudo"
-- sin discriminador de tabla: sin esta tabla habría que inferir el origen desde
-- el tipo de movimiento y no quedaría registro de qué línea produjo qué entrada.
--
-- Las filas de tipo RECUPERACION nunca se borran al anular: se agrega una fila
-- REVERSA_ANULACION apuntando al movimiento inverso. El historial de inventario
-- es append-only, igual que el de eventos.
CREATE TABLE nota_credito_movimiento (
    id                       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                BIGINT      NOT NULL REFERENCES tenant(id),
    nota_credito_id          BIGINT      NOT NULL REFERENCES nota_credito(id) ON DELETE CASCADE,
    nota_credito_detalle_id  BIGINT      REFERENCES nota_credito_detalle(id) ON DELETE CASCADE,
    movimiento_inventario_id BIGINT      NOT NULL REFERENCES movimiento_inventario(id),
    tipo                     VARCHAR(20) NOT NULL,
    fecha                    TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX idx_nota_credito_movimiento_nota ON nota_credito_movimiento(nota_credito_id, fecha);

-- TipoMovimiento gana ENTRADA_NOTA_CREDITO (20 caracteres) y
-- SALIDA_ANULA_NOTA_CREDITO (25). La columna era VARCHAR(20) y no alcanza.
ALTER TABLE movimiento_inventario        ALTER COLUMN tipo TYPE VARCHAR(30);
ALTER TABLE movimiento_inventario_header ALTER COLUMN tipo TYPE VARCHAR(30);
