-- Módulo de Nota de Débito: el documento que anula o revierte una Nota de
-- Crédito ya emitida, revirtiendo sus efectos: montos y, si la NC recuperó
-- mercadería, la recuperación de inventario.
--
-- Cadena completa de trazabilidad:
--     Documento original (Venta) -> Nota de Crédito -> Nota de Débito
-- Y cuando hay impacto de inventario:
--     Venta -> NC -> Movimiento de inventario (ENTRADA_NOTA_CREDITO)
--           -> ND -> Movimiento de reversión (SALIDA_NOTA_CREDITO)
--
-- El número (ND-000012) se arma en la aplicación a partir de "folio", un
-- correlativo por tenant servido por nota_debito_folio_contador. Se asigna al
-- crear y nunca se reutiliza, igual que en notas de crédito.
--
-- Alcance deliberado: sin XML, DTE, CAF ni envío al SII, y sin efectos sobre
-- cuentas por cobrar ni tesorería. La nota de débito revierte la Nota de
-- Crédito asociada; nada más.

CREATE TABLE nota_debito_folio_contador (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT  NOT NULL REFERENCES tenant(id),
    ultimo_folio INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_nota_debito_folio_tenant UNIQUE (tenant_id)
);

CREATE TABLE nota_debito (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT        NOT NULL REFERENCES tenant(id),
    folio               INTEGER       NOT NULL,
    cliente_id          BIGINT        NOT NULL REFERENCES cliente(id),
    usuario_id          BIGINT        NOT NULL REFERENCES usuario(id),
    estado              VARCHAR(20)   NOT NULL DEFAULT 'BORRADOR',
    tipo_reversion      VARCHAR(20)   NOT NULL,
    fecha               DATE          NOT NULL,
    motivo              VARCHAR(500),
    observaciones       VARCHAR(500),
    -- Solo se usa cuando tipo_reversion = 'REVIERTE_TEXTO'.
    texto_correccion    VARCHAR(2000),
    -- Bodega a la que pertenece la mercadería que la NC recuperó y que esta ND
    -- devuelve a su lugar: la misma de la venta original, heredada de la NC.
    bodega_id           BIGINT        REFERENCES bodega(id),
    exenta              BOOLEAN       NOT NULL DEFAULT false,
    moneda              VARCHAR(10)   NOT NULL DEFAULT 'CLP',

    -- Documento asociado: FK dura a la Nota de Crédito más snapshot histórico.
    -- nota_credito_id es la FK hacia el documento vivo; los campos nc_* son la
    -- fotografía del momento de creación, porque la cadena Venta -> NC -> ND
    -- debe quedar congelada aunque los documentos originales cambien después.
    nota_credito_id     BIGINT        NOT NULL REFERENCES nota_credito(id),
    nc_doc_asociado_tipo VARCHAR(20)  NOT NULL,
    nc_folio            INTEGER,
    nc_fecha            DATE,
    nc_monto_total      NUMERIC(14,2),
    nc_razon            VARCHAR(500),

    -- Todos los montos se guardan positivos: el signo semántico lo da el tipo de
    -- documento, una nota de débito por definición revierte una nota de crédito.
    descuento           NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_subtotal      NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_descuento     NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_neto          NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_iva           NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_total         NUMERIC(14,2) NOT NULL DEFAULT 0,

    fecha_emision       TIMESTAMP,
    fecha_anulacion     TIMESTAMP,
    fecha_creacion      TIMESTAMP     NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT uq_nota_debito_tenant_folio UNIQUE (tenant_id, folio),
    CONSTRAINT ck_nota_debito_descuento_no_negativo CHECK (descuento >= 0)
);
CREATE INDEX idx_nota_debito_tenant_estado  ON nota_debito(tenant_id, estado);
CREATE INDEX idx_nota_debito_tenant_fecha   ON nota_debito(tenant_id, fecha);
CREATE INDEX idx_nota_debito_cliente        ON nota_debito(tenant_id, cliente_id);
CREATE INDEX idx_nota_debito_nc             ON nota_debito(tenant_id, nota_credito_id);
CREATE INDEX idx_nota_debito_tipo           ON nota_debito(tenant_id, tipo_reversion);

CREATE TABLE nota_debito_detalle (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_debito_id           BIGINT        NOT NULL REFERENCES nota_debito(id) ON DELETE CASCADE,
    -- Línea de la nota de crédito que esta línea revierte. Es nulo cuando la
    -- reversión se asocia a información no vinculada a una línea de la NC; esas
    -- líneas no pueden revertir inventario porque no hay cantidad contra la que
    -- validar.
    nota_credito_detalle_id  BIGINT        REFERENCES nota_credito_detalle(id),
    producto_id              BIGINT        NOT NULL REFERENCES producto(id),
    codigo                   VARCHAR(50),
    descripcion              VARCHAR(255)  NOT NULL,
    cantidad                 NUMERIC(14,2) NOT NULL,
    precio_unitario          NUMERIC(14,2) NOT NULL,
    descuento                NUMERIC(14,2) NOT NULL DEFAULT 0,
    subtotal                 NUMERIC(14,2) NOT NULL,
    -- Si esta línea impacta inventario al emitir la nota de débito (revierte la
    -- recuperación que hizo la NC). Se hereda de la línea de la NC original.
    revierte_inventario      BOOLEAN       NOT NULL DEFAULT true,
    CONSTRAINT ck_nota_debito_detalle_cantidad  CHECK (cantidad > 0),
    CONSTRAINT ck_nota_debito_detalle_precio    CHECK (precio_unitario >= 0),
    CONSTRAINT ck_nota_debito_detalle_descuento CHECK (descuento >= 0)
);
CREATE INDEX idx_nota_debito_detalle_nd  ON nota_debito_detalle(nota_debito_id);
CREATE INDEX idx_nota_debito_detalle_ncd ON nota_debito_detalle(nota_credito_detalle_id);

CREATE TABLE nota_debito_evento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL REFERENCES tenant(id),
    nota_debito_id  BIGINT      NOT NULL REFERENCES nota_debito(id) ON DELETE CASCADE,
    usuario_id      BIGINT      REFERENCES usuario(id),
    accion          VARCHAR(30) NOT NULL,
    estado_anterior VARCHAR(20),
    estado_nuevo    VARCHAR(20),
    detalle         VARCHAR(500),
    fecha           TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX idx_nota_debito_evento_nd ON nota_debito_evento(nota_debito_id, fecha);

CREATE TABLE nota_debito_movimiento (
    id                       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                BIGINT      NOT NULL REFERENCES tenant(id),
    nota_debito_id           BIGINT      NOT NULL REFERENCES nota_debito(id) ON DELETE CASCADE,
    nota_debito_detalle_id   BIGINT      REFERENCES nota_debito_detalle(id) ON DELETE CASCADE,
    movimiento_inventario_id BIGINT      NOT NULL REFERENCES movimiento_inventario(id),
    tipo                     VARCHAR(20) NOT NULL,
    fecha                    TIMESTAMP   NOT NULL DEFAULT now()
);
CREATE INDEX idx_nota_debito_movimiento_nd ON nota_debito_movimiento(nota_debito_id, fecha);