-- Stock pasa a manejarse por bodega en vez de directo en producto.

CREATE TABLE bodega (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    nombre          VARCHAR(150) NOT NULL,
    principal       BOOLEAN      NOT NULL DEFAULT FALSE,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_bodega_tenant ON bodega(tenant_id);

CREATE TABLE stock_producto_bodega (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    producto_id     BIGINT NOT NULL REFERENCES producto(id),
    bodega_id       BIGINT NOT NULL REFERENCES bodega(id),
    cantidad        NUMERIC(14,2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_stock_producto_bodega UNIQUE (producto_id, bodega_id)
);
CREATE INDEX idx_stock_tenant ON stock_producto_bodega(tenant_id);
CREATE INDEX idx_stock_producto ON stock_producto_bodega(producto_id);

-- Bodega principal por tenant existente
INSERT INTO bodega (tenant_id, nombre, principal)
SELECT id, 'Principal', TRUE FROM tenant;

-- Migra el stock actual del producto a su bodega principal
INSERT INTO stock_producto_bodega (tenant_id, producto_id, bodega_id, cantidad)
SELECT p.tenant_id, p.id, b.id, p.stock
FROM producto p
JOIN bodega b ON b.tenant_id = p.tenant_id AND b.principal = TRUE;

ALTER TABLE producto DROP COLUMN stock;
ALTER TABLE producto DROP COLUMN controla_stock;
