-- Mantenedor de categorías y subcategorías, enlazado opcionalmente a producto
-- (no hay datos de texto libre que migrar: este proyecto nunca tuvo esos campos).

CREATE TABLE categoria (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    nombre          VARCHAR(100) NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_categoria_tenant_nombre UNIQUE (tenant_id, nombre)
);
CREATE INDEX idx_categoria_tenant ON categoria(tenant_id);

CREATE TABLE subcategoria (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    categoria_id    BIGINT NOT NULL REFERENCES categoria(id),
    nombre          VARCHAR(100) NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_subcategoria_categoria_nombre UNIQUE (categoria_id, nombre)
);
CREATE INDEX idx_subcategoria_tenant ON subcategoria(tenant_id);
CREATE INDEX idx_subcategoria_categoria ON subcategoria(categoria_id);

ALTER TABLE producto ADD COLUMN categoria_id BIGINT REFERENCES categoria(id);
ALTER TABLE producto ADD COLUMN subcategoria_id BIGINT REFERENCES subcategoria(id);
