-- Mantenedor de formas de pago (nombre + categoría: GRATIS, CREDITO, CONTADO).
-- No se enlaza a "venta" como en slime-erp_old porque ese módulo no existe aquí todavía.

CREATE TABLE forma_pago (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    nombre          VARCHAR(100) NOT NULL,
    categoria       VARCHAR(20)  NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_forma_pago_tenant_nombre UNIQUE (tenant_id, nombre)
);
CREATE INDEX idx_forma_pago_tenant ON forma_pago(tenant_id);

INSERT INTO forma_pago (tenant_id, nombre, categoria)
SELECT id, 'Efectivo', 'CONTADO' FROM tenant
UNION ALL
SELECT id, 'Crédito', 'CREDITO' FROM tenant
UNION ALL
SELECT id, 'Cortesía', 'GRATIS' FROM tenant;
