-- Movimientos de inventario: cabecera (agrupa un movimiento con uno o más ítems)
-- y detalle por producto/bodega. A diferencia de slime-erp_old, se crea directamente
-- con la forma final (header_id y bodega_id incluidos desde el inicio) porque acá
-- no existe la tabla original sin esas columnas que migrar.

CREATE TABLE movimiento_inventario_header (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL REFERENCES tenant(id),
    tipo                VARCHAR(20)  NOT NULL,
    bodega_origen_id    BIGINT       REFERENCES bodega(id),
    bodega_destino_id   BIGINT       REFERENCES bodega(id),
    usuario_id          BIGINT       NOT NULL REFERENCES usuario(id),
    observacion         VARCHAR(500),
    fecha               TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_mih_tenant ON movimiento_inventario_header(tenant_id);
CREATE INDEX idx_mih_fecha  ON movimiento_inventario_header(tenant_id, fecha);

CREATE TABLE movimiento_inventario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    producto_id     BIGINT NOT NULL REFERENCES producto(id),
    tipo            VARCHAR(20)  NOT NULL,
    cantidad        NUMERIC(14,2) NOT NULL,
    referencia_id   BIGINT,
    header_id       BIGINT REFERENCES movimiento_inventario_header(id),
    bodega_id       BIGINT REFERENCES bodega(id),
    fecha           TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_movinv_tenant ON movimiento_inventario(tenant_id);
CREATE INDEX idx_movinv_producto ON movimiento_inventario(producto_id);
CREATE INDEX idx_movinv_header ON movimiento_inventario(header_id);
