-- Mantenedor de proveedores, análogo a Cliente pero sin los campos DTE
-- (el proveedor no es receptor de la factura que emite el tenant).

CREATE TABLE proveedor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL REFERENCES tenant(id),
    nombre          VARCHAR(150) NOT NULL,
    rut             VARCHAR(20),
    email           VARCHAR(150),
    telefono        VARCHAR(30),
    direccion       VARCHAR(255),
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX idx_proveedor_tenant ON proveedor(tenant_id);
