-- Ventas: cabecera con el tipo de documento (BOLETA/FACTURA/VOUCHER) y su
-- desglose neto/IVA/total ya calculado, más el detalle de líneas.
-- No tiene relación con la facturación electrónica (folios SII, CAF, etc.);
-- es una clasificación interna que determina cómo se leen los montos.

CREATE TABLE venta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(id),
    cliente_id      BIGINT       NOT NULL REFERENCES cliente(id),
    forma_pago_id   BIGINT       NOT NULL REFERENCES forma_pago(id),
    bodega_id       BIGINT       NOT NULL REFERENCES bodega(id),
    tipo_documento  VARCHAR(20)  NOT NULL,
    exento          BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha           TIMESTAMP    NOT NULL DEFAULT now(),
    monto_neto      NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_iva       NUMERIC(14,2) NOT NULL DEFAULT 0,
    monto_total     NUMERIC(14,2) NOT NULL DEFAULT 0,
    descuento       NUMERIC(14,2) NOT NULL DEFAULT 0,
    observacion     VARCHAR(500),
    activo          BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_venta_tenant ON venta(tenant_id);
CREATE INDEX idx_venta_fecha ON venta(tenant_id, fecha);
CREATE INDEX idx_venta_cliente ON venta(cliente_id);

CREATE TABLE venta_detalle (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id        BIGINT NOT NULL REFERENCES venta(id),
    producto_id     BIGINT NOT NULL REFERENCES producto(id),
    cantidad        NUMERIC(14,2) NOT NULL,
    precio_unitario NUMERIC(14,2) NOT NULL,
    subtotal        NUMERIC(14,2) NOT NULL
);
CREATE INDEX idx_venta_detalle_venta ON venta_detalle(venta_id);
